version: "3"
services:
  nginx:
    container_name: nginx
    image: antonioanerao/nginx:alpine
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./data:/laravel
      - ./logs/nginx:/var/log/nginx/

  php:
    container_name: php
    image: antonioanerao/php:fpm-alpine
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/laravel
      - ./logs/php.log:/var/log/fpm-php.www.log

networks:
  internal:
    driver: bridge
