version: "3"
services:
  nginx:
    container_name: nginx
    image: ${IMAGEM_NGINX_DEV_NOME}:${IMAGEM_NGINX_DEV_VERSAO}
    build:
      context: .
      dockerfile: build/dev/nginx/Dockerfile
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./data:/laravel
      - ./logs/nginx:/var/log/nginx/

  php:
    container_name: php
    image: ${IMAGEM_PHP_DEV_NOME}:${IMAGEM_PHP_DEV_VERSAO}
    build:
      context: .
      dockerfile: build/dev/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/laravel
      - ./logs/php:/var/log/fpm-php.www.log

networks:
  internal:
    driver: bridge
